/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nr_consult;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author tojo
 */
public class conge extends javax.swing.JFrame {
Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
     static String test;
    static String te;
    int xMouse;
      int yMouse;
    /**
     * Creates new form conge
     */
    public conge() {
       conn = ConexionBD.Conexion();
        initComponents();
         
          Affichage();
          
    }
     public void Affichage() {
        try {
            String requete = "Select * from conge ";
            ps = conn.prepareStatement(requete);
            rs = ps.executeQuery();
            table_conge.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            System.out.println(e);
        }
        }
      public void Deplace() {
        try {

            int row = table_conge.getSelectedRow();
            this.test = (table_conge.getModel().getValueAt(row, 0).toString());
            String requet = " select * from  conge where id_conge = '" + test + "' ";
            ps = conn.prepareStatement(requet);
            rs = ps.executeQuery();

            if (rs.next()) {
                String t1 = rs.getString("id_conge");
                txt_id.setText(t1);
                String t2 = rs.getString("nom_employe");
                txt_nom.setText(t2);
                String t3 = rs.getString("prenom_employe");
                txt_prenom.setText(t3);
                String t4 = rs.getString("date_demande");
                txt_date1.setText(t4);
                String t5 = rs.getString("date_debut");
                txt_date2.setText(t5);
                String t6 = rs.getString("date_retour");
                txt_date3.setText(t6);
                String t7 = rs.getString("nombre_jour");
                nbj.setText(t7);
                String t8 = rs.getString("reste");
                nbj1.setText(t8);
                String t9 =rs.getString("motif");
                txt_motif.setText(t9);
                String t10 = rs.getString("etat");
                txt_etat.setText(t10);
                
              
            }
ps.close();
                rs.close();
        } catch (Exception e) {
            System.out.println(e);
            
        }finally {

            try {
                ps.close();
                rs.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erreur BD");
            }
        }
    }

    public String gettableresult() {
        return test;
    }
    public void clear(){
        try{  txt_id.setText("");
        txt_nom.setText("");
            
          txt_prenom.setText("");
          
          txt_date1.setText("");
          txt_date2.setText("");
          txt_date3.setText("");
          txt_etat.setText("");
          nbj.setText("");
          nbj1.setText("");
          txt_motif.setText("");
          txt_etat.setText("");
        
        }catch (Exception e) {
           
            System.out.println("--> SQLException : " + e);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_conge = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        txt_prenom = new javax.swing.JTextField();
        txt_date1 = new javax.swing.JTextField();
        txt_date2 = new javax.swing.JTextField();
        txt_date3 = new javax.swing.JTextField();
        nbj = new javax.swing.JTextField();
        nbj1 = new javax.swing.JTextField();
        txt_motif = new javax.swing.JTextField();
        txt_etat = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        bntactualiser = new javax.swing.JButton();
        btnok = new javax.swing.JButton();
        btnsuppr = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        table_conge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_conge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_congeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_conge);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 110, 1060, 240);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("GESTION DE CONGE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 40, 410, 50);

        jLabel2.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel2.setText("Etat                                     :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 570, 210, 40);

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel3.setText("ID congé                             : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 390, 210, 40);

        jLabel4.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel4.setText("Nom de l'employé        :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 430, 210, 40);

        jLabel5.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel5.setText("Prenom de l'employé :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 480, 210, 40);

        jLabel6.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel6.setText("Date du demande        :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 520, 210, 40);

        jLabel7.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel7.setText("Date de  debut              :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 570, 210, 40);

        jLabel8.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel8.setText("Date de retour             :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 394, 210, 40);

        jLabel9.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel9.setText("Nombre de jour             :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(440, 434, 210, 40);

        jLabel10.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel10.setText("Reste du congé            :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 484, 210, 40);

        jLabel11.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel11.setText("Motif                                   :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 530, 210, 40);

        txt_nom.setEditable(false);
        getContentPane().add(txt_nom);
        txt_nom.setBounds(250, 440, 170, 30);

        txt_prenom.setEditable(false);
        getContentPane().add(txt_prenom);
        txt_prenom.setBounds(250, 490, 170, 30);

        txt_date1.setEditable(false);
        getContentPane().add(txt_date1);
        txt_date1.setBounds(250, 530, 170, 30);

        txt_date2.setEditable(false);
        getContentPane().add(txt_date2);
        txt_date2.setBounds(250, 580, 170, 30);

        txt_date3.setEditable(false);
        getContentPane().add(txt_date3);
        txt_date3.setBounds(650, 400, 170, 30);

        nbj.setEditable(false);
        getContentPane().add(nbj);
        nbj.setBounds(650, 440, 170, 30);
        getContentPane().add(nbj1);
        nbj1.setBounds(650, 490, 170, 30);

        txt_motif.setEditable(false);
        getContentPane().add(txt_motif);
        txt_motif.setBounds(650, 530, 170, 30);
        getContentPane().add(txt_etat);
        txt_etat.setBounds(650, 580, 170, 30);

        txt_id.setEditable(false);
        getContentPane().add(txt_id);
        txt_id.setBounds(250, 400, 170, 30);

        jButton1.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(890, 580, 190, 30);

        bntactualiser.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        bntactualiser.setText("Actualiser");
        bntactualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntactualiserActionPerformed(evt);
            }
        });
        getContentPane().add(bntactualiser);
        bntactualiser.setBounds(890, 490, 190, 30);

        btnok.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });
        getContentPane().add(btnok);
        btnok.setBounds(890, 400, 190, 30);

        btnsuppr.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        btnsuppr.setText("Supprimer");
        btnsuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprActionPerformed(evt);
            }
        });
        getContentPane().add(btnsuppr);
        btnsuppr.setBounds(890, 450, 190, 30);

        jButton5.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jButton5.setText("Imprimer");
        getContentPane().add(jButton5);
        jButton5.setBounds(890, 530, 190, 30);

        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19);
        jLabel19.setBounds(1090, 0, 30, 30);

        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel13MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 1080, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nr/imageNR/5.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 1120, 680);

        setSize(new java.awt.Dimension(1119, 671));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntactualiserActionPerformed
Affichage();
clear();
// TODO add your handling code here:
    }//GEN-LAST:event_bntactualiserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 admin s = new admin();
s.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void table_congeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_congeMouseClicked
Deplace();        // TODO add your handling code here:
    }//GEN-LAST:event_table_congeMouseClicked

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
String t1 = txt_id.getText();

        try { 
            String requete = "update conge set nombre_jour=?, etat=? where  id_conge ='" + t1 + "'";
       
            ps = conn.prepareStatement(requete);
            ps.setString(1, nbj1.getText());
            ps.setString(2, txt_etat.getText());
           
           
           ps.execute();
            ps.execute();
             clear();
        Affichage();
            JOptionPane.showMessageDialog(null, "OK");
 ps.close();
                rs.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }finally {

            try {
                ps.close();
                rs.close();
               

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "errer");
            }
        }         // TODO add your handling code here:
    }//GEN-LAST:event_btnokActionPerformed

    private void btnsupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprActionPerformed
 try {
            if (JOptionPane.showConfirmDialog(null, "attention vous devez suprimer une congé,est ce que vous êtes sur?",
                    "Supprimer Congé", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                if (txt_id.getText().length() != 0) {

                    String requete = "delete from conge where id_conge = ?";
                    ps = conn.prepareStatement(requete);
                    ps.setString(1, txt_id.getText());
                    ps.execute();
                    System.out.println("deleted");
                    //JOptionPane.showMessageDialog(null,"deleted");
                    
                } else {
                    JOptionPane.showMessageDialog(null, "veuillez choisir  une congé !");
                }
            }
              ps.close();
                rs.close();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "erreur de supprimer \n" + e.getMessage());
        }finally {

            try {
                ps.close();
                rs.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erreur BD");
            }
        }
 
       
        Affichage();        // TODO add your handling code here:
    }//GEN-LAST:event_btnsupprActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
admin g = new admin();
g.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel13MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation( x - xMouse , y - yMouse);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conge().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntactualiser;
    private javax.swing.JButton btnok;
    private javax.swing.JButton btnsuppr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nbj;
    private javax.swing.JTextField nbj1;
    private javax.swing.JTable table_conge;
    private javax.swing.JTextField txt_date1;
    private javax.swing.JTextField txt_date2;
    private javax.swing.JTextField txt_date3;
    private javax.swing.JTextField txt_etat;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_motif;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prenom;
    // End of variables declaration//GEN-END:variables
}
