/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nr_consult;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author tojo
 */
public class pointage extends javax.swing.JFrame {
Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
     static String test;
    /**
     * Creates new form pointage
     */
    public pointage() {
        conn = ConexionBD.Conexion();
        initComponents();
         Affichage();
         btnsuppr.setEnabled(false);
    }
 public void Affichage() {
        try {
            String requete = "Select * from pointage ";
            ps = conn.prepareStatement(requete);
            rs = ps.executeQuery();
            table_pointage.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            System.out.println(e);
        }
        }
 
 public void Deplace() {
        try {

            int row = table_pointage.getSelectedRow();
            this.test = (table_pointage.getModel().getValueAt(row, 0).toString());
            String requet = " select * from  pointage where id_pointage = '" + test + "' ";
            ps = conn.prepareStatement(requet);
            rs = ps.executeQuery();

            if (rs.next()) {
                String t1 = rs.getString("id_pointage");
                txt_id.setText(t1);
               String t2 = rs.getString("nom_employe");
                txt_nom.setText(t2);
                String t3 = rs.getString("prenom_employe");
                txt_prenom.setText(t3);
                String t4 = rs.getString("date_entre");
                txt_date.setText(t4);
                String t5 = rs.getString("heure_entre");
                txt_he.setText(t5);
                String t6 = rs.getString("heure_sortie");
                txt_hs.setText(t6);
                
                String t7 = rs.getString("etat");
                txt_e.setText(t7);
                
//                byte[] imagedata =rs.getBytes("image");
//                Format = new ImageIcon(imagedata);
//                image.setIcon(Format);
                
            }
ps.close();
                rs.close();
        } catch (Exception e) {
            System.out.println(e);
            
        }finally {

            try {
                ps.close();
                rs.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erreur BD");
            }
        }
    }

    public String gettableresult() {
        return test;
    }
    public void Clear() {
        txt_id.setText("");
        txt_nom.setText("");
        txt_prenom.setText("");
        txt_date.setText("");
        txt_he.setText("");
        txt_hs.setText("");
        txt_e.setText("");
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_pointage = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nom = new javax.swing.JTextField();
        txt_prenom = new javax.swing.JTextField();
        txt_he = new javax.swing.JTextField();
        txt_hs = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        txtrechercher = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_e = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnsuppr = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        table_pointage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_pointage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_pointageMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                table_pointageMouseReleased(evt);
            }
        });
        table_pointage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_pointageKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table_pointage);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 80, 810, 200);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        jLabel1.setText("Id pointage         :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 290, 140, 40);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        jLabel2.setText("Nom employé    :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 340, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        jLabel3.setText("Prenom employé :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 390, 140, 40);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("Gestion de pointage");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 10, 250, 50);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        jLabel5.setText("Heure de sortie :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(510, 350, 140, 50);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        jLabel6.setText("Etat                  :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(510, 400, 140, 40);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        jLabel7.setText("Date d'entrer       :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 440, 140, 40);

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(255, 255, 255));
        txt_id.setBorder(null);
        getContentPane().add(txt_id);
        txt_id.setBounds(240, 300, 260, 30);

        txt_nom.setEditable(false);
        txt_nom.setBackground(new java.awt.Color(255, 255, 255));
        txt_nom.setBorder(null);
        getContentPane().add(txt_nom);
        txt_nom.setBounds(240, 350, 260, 30);

        txt_prenom.setEditable(false);
        txt_prenom.setBackground(new java.awt.Color(255, 255, 255));
        txt_prenom.setBorder(null);
        getContentPane().add(txt_prenom);
        txt_prenom.setBounds(240, 390, 260, 30);

        txt_he.setEditable(false);
        txt_he.setBackground(new java.awt.Color(255, 255, 255));
        txt_he.setBorder(null);
        getContentPane().add(txt_he);
        txt_he.setBounds(620, 300, 260, 30);

        txt_hs.setEditable(false);
        txt_hs.setBackground(new java.awt.Color(255, 255, 255));
        txt_hs.setBorder(null);
        getContentPane().add(txt_hs);
        txt_hs.setBounds(620, 360, 260, 30);

        txt_date.setEditable(false);
        txt_date.setBackground(new java.awt.Color(255, 255, 255));
        txt_date.setBorder(null);
        getContentPane().add(txt_date);
        txt_date.setBounds(240, 440, 260, 30);

        txtrechercher.setBorder(null);
        txtrechercher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtrechercherMouseClicked(evt);
            }
        });
        txtrechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrechercherActionPerformed(evt);
            }
        });
        txtrechercher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrechercherKeyReleased(evt);
            }
        });
        getContentPane().add(txtrechercher);
        txtrechercher.setBounds(680, 20, 240, 20);

        txt_e.setColumns(20);
        txt_e.setRows(5);
        jScrollPane2.setViewportView(txt_e);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(620, 410, 260, 60);

        jButton1.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 500, 160, 40);

        jButton2.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jButton2.setText("Retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 20, 160, 30);

        jButton3.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jButton3.setText("Imprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(660, 500, 160, 40);

        btnsuppr.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        btnsuppr.setText("Supprimer");
        btnsuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprActionPerformed(evt);
            }
        });
        getContentPane().add(btnsuppr);
        btnsuppr.setBounds(300, 500, 160, 40);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        jLabel8.setText("Heure d'entrer :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(510, 290, 140, 50);

        jButton5.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jButton5.setText("Actualiser");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(490, 500, 130, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nr_consult/z22.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(670, 10, 280, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nr/imageNR/3.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 970, 590);

        setSize(new java.awt.Dimension(987, 621));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtrechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrechercherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrechercherActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String t1 = txt_id.getText();

        try { 
            String requete = "update pointage set id_pointage=? , etat=? where  id_pointage  ='" + t1 + "'";
       
            ps = conn.prepareStatement(requete);
            ps.setString(1, txt_id.getText());
            ps.setString(2, txt_e.getText());
           
           
           ps.execute();
            ps.execute();
             Clear();
        Affichage();
            JOptionPane.showMessageDialog(null, "OK");
 ps.close();
                rs.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }finally {

            try {
                ps.close();
                rs.close();
               

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "errer");
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void table_pointageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pointageMouseClicked
btnsuppr.setEnabled(true);   Deplace();            // TODO add your handling code here:
    }//GEN-LAST:event_table_pointageMouseClicked

    private void table_pointageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_pointageKeyReleased
 Deplace();
       // TODO add your handling code here:
    }//GEN-LAST:event_table_pointageKeyReleased

    private void table_pointageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pointageMouseReleased
 Deplace();         // TODO add your handling code here:
    }//GEN-LAST:event_table_pointageMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 admin k = new admin();
k.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Affichage();
btnsuppr.setEnabled(false);
Clear();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnsupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprActionPerformed
try {
            if (JOptionPane.showConfirmDialog(null, "attention vous devez suprimer un pointage,est ce que vous êtes sur?",
                    "Supprimer le pointage", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                if (txt_id.getText().length() != 0) {

                    String requete = "delete from pointage where id_pointage = ?";
                    ps = conn.prepareStatement(requete);
                    ps.setString(1, txt_id.getText());
                    ps.execute();
                    System.out.println("deleted");
                    //JOptionPane.showMessageDialog(null,"deleted");
                    
                } else {
                    JOptionPane.showMessageDialog(null, "veuillez choisir  un pointage !");
                }
            }
              ps.close();
                rs.close();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "erreur de supprimer \n" + e.getMessage());
        }finally {

            try {
                ps.close();
                rs.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erreur BD");
            }
        } 
       
Clear();
        Affichage();
         // TODO add your handling code here:
    }//GEN-LAST:event_btnsupprActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        MessageFormat header = new MessageFormat("Fiche de pointage :");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            table_pointage.print(JTable.PrintMode.NORMAL, header, footer);

        } catch (java.awt.print.PrinterException e) {
            System.err.format("Erreur d'impression ", e.getMessage());
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtrechercherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrechercherKeyReleased
try {
String requete = "select * from  pointage where nom_employe LIKE ?" ;
            ps = conn.prepareStatement(requete);
            ps.setString(1, "%"+txtrechercher.getText()+"%");
            rs = ps.executeQuery();
            table_pointage.setModel(DbUtils.resultSetToTableModel(rs));
//             byte[] imagedata =rs.getBytes("image");
//                Format = new ImageIcon(imagedata);
//                image.setIcon(Format);
             ps.close();
                rs.close();
        } catch (Exception e) {
            System.out.println(e);
        }finally {

            try {
                ps.close();
                rs.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erreur BD");
            }
        }     // TODO add your handling code here:
    }//GEN-LAST:event_txtrechercherKeyReleased

    private void txtrechercherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrechercherMouseClicked
Affichage();  
Clear();        // TODO add your handling code here:
    }//GEN-LAST:event_txtrechercherMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pointage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pointage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsuppr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_pointage;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextArea txt_e;
    private javax.swing.JTextField txt_he;
    private javax.swing.JTextField txt_hs;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prenom;
    private javax.swing.JTextField txtrechercher;
    // End of variables declaration//GEN-END:variables
}
