/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nr_consult;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author tojo
 */
public class Service extends javax.swing.JFrame {
  Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    static String test ;
    int xMouse;
      int yMouse;
    /**
     * Creates new form Fonction
     */
    public Service() {
        conn = ConexionBD.Conexion();
        initComponents();
        Affichage();
        btnajout.setEnabled(true);
        btnmodif.setEnabled(false);
        btnsuppr.setEnabled(false);
        
    }

 public void Affichage() {
        try {
            String requete = "Select * from service ";
            ps = conn.prepareStatement(requete);
            rs = ps.executeQuery();
            table_service.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            System.out.println(e);
        }
        }
 
 public void Deplace() {
        try {

            int row = table_service.getSelectedRow();
            this.test = (table_service.getModel().getValueAt(row, 0).toString());
            String requet = " select * from  service where id_service = '" + test + "' ";
            ps = conn.prepareStatement(requet);
            rs = ps.executeQuery();

            if (rs.next()) {
                String t1 = rs.getString("id_service");
                txt_id.setText(t1);
               String t2 = rs.getString("service");
                txt_service.setText(t2);
                
            }
ps.close();
                rs.close();
        } catch (Exception e) {
            System.out.println(e);
            
        }finally {

            try {
                ps.close();
                rs.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erreur BD");
            }
        }
    }

    public String gettableresult() {
        return test;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_service = new javax.swing.JTable();
        txt_service = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnajout = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnmodif = new javax.swing.JButton();
        btnsuppr = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        table_service.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_service.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_serviceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_service);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 57, 710, 210);
        getContentPane().add(txt_service);
        txt_service.setBounds(320, 360, 250, 40);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel1.setText(" Id service :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 300, 120, 30);

        btnajout.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        btnajout.setText("Ajouter");
        btnajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnajout);
        btnajout.setBounds(90, 450, 140, 40);

        txt_id.setEditable(false);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id);
        txt_id.setBounds(320, 300, 250, 40);

        jLabel2.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jLabel2.setText("Service :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 360, 120, 30);

        btnmodif.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        btnmodif.setText("Modifier");
        btnmodif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodif);
        btnmodif.setBounds(240, 450, 140, 40);

        btnsuppr.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        btnsuppr.setText("Supprimer");
        btnsuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprActionPerformed(evt);
            }
        });
        getContentPane().add(btnsuppr);
        btnsuppr.setBounds(390, 450, 160, 40);

        jButton5.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        jButton5.setText("Actualiser");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(560, 450, 160, 40);

        jLabel6.setFont(new java.awt.Font("Tekton Pro Ext", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("                               SERVICE");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel6MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 760, 30);

        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19);
        jLabel19.setBounds(770, 0, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nr/imageNR/4.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-6, -6, 816, 580);

        setSize(new java.awt.Dimension(811, 571));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void btnajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajoutActionPerformed
if (txt_service.getText().equals("") ) {
            JOptionPane.showMessageDialog(this, "SVP entrer les informations complete");
        } else {
        try {
           
           String requete = "insert into service (service) values (?)";
            ps = conn.prepareStatement(requete);
            ps.setString(1, txt_service.getText());
          
            ps.execute();
 txt_service.setText("");
        Affichage();
            JOptionPane.showMessageDialog(null, "Enregistrement avec succès");
 ps.close();
                rs.close();
           Affichage();

        } catch (Exception e) {
            System.out.println("--> SQLException : " + e);
           
       
        }
        }   
// TODO add your handling code here:
    }//GEN-LAST:event_btnajoutActionPerformed

    private void table_serviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_serviceMouseClicked
btnajout.setEnabled(false);

        btnmodif.setEnabled(true);
        btnsuppr.setEnabled(true);
Deplace();        // TODO add your handling code here:
    }//GEN-LAST:event_table_serviceMouseClicked

    private void btnmodifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifActionPerformed
String t1 = txt_id.getText();

        try { 
            String requete = "update service set id_service=?, service=? where  id_service ='" + t1 + "'";
       
            ps = conn.prepareStatement(requete);
            ps.setString(1, txt_id.getText());
            ps.setString(2, txt_service.getText());
           
           
           ps.execute();
            ps.execute();
             txt_service.setText("");
        Affichage();
            JOptionPane.showMessageDialog(null, "Modification avec succès");
 ps.close();
                rs.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }finally {

            try {
                ps.close();
                rs.close();
                txt_id.setText("");
                txt_service.setText("");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "errer");
            }
        }              // TODO add your handling code here:
    }//GEN-LAST:event_btnmodifActionPerformed

    private void btnsupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprActionPerformed
   try {
            if (JOptionPane.showConfirmDialog(null, "attention vous devez suprimer une service,est ce que vous êtes sur?",
                    "Supprimer Service", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                if (txt_id.getText().length() != 0) {

                    String requete = "delete from service where id_service = ?";
                    ps = conn.prepareStatement(requete);
                    ps.setString(1, txt_id.getText());
                    ps.execute();
                    System.out.println("deleted");
                    //JOptionPane.showMessageDialog(null,"deleted");
                    
                } else {
                    JOptionPane.showMessageDialog(null, "veuillez choisir  une service !");
                }
            }
              ps.close();
                rs.close();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "erreur de supprimer \n" + e.getMessage());
        }finally {

            try {
                ps.close();
                rs.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "erreur BD");
            }
        } 
       
//        btninscri.setEnabled(false);
        Affichage();
               // TODO add your handling code here:
    }//GEN-LAST:event_btnsupprActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Affichage();
btnajout.setEnabled(true);
        btnmodif.setEnabled(false);
        btnsuppr.setEnabled(false);
        txt_id.setText("");
txt_service.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation( x - xMouse , y - yMouse);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseDragged

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
     admin a =new admin();
     a.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Service.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Service().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajout;
    private javax.swing.JButton btnmodif;
    private javax.swing.JButton btnsuppr;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_service;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_service;
    // End of variables declaration//GEN-END:variables
}
